version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    working_directory: /root/project/SPECHT.jl   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.7
    steps:
      - run:
          command: julia -e 'using Pkg; Pkg.add(url="https://github.com/bencardoen/SPECHT.jl.git")'
